### PR TITLE
148 sardine gui

### PR DESCRIPTION
**Pull request by johnchem**
Modification of the logger to add the logging library. The print statement in the program could be now decline in : 
print() : print in the console without notification in the log file

logging.debug() : print only in the log file
logging.info() : print only in the log file

logging.warning() : print both in log file and in the console
logging.error() : print both in log file and in the console
logging.critical() : print both in log file and in the console

the format of the console message is <LEVEL> - <MESSAGE>
in the log file : <%d/%m/%Y %H:%M:%S"> | <LEVEL> | <MESSAGE>
the rich markdown is still supported into the console.

### CODE REVIEW

**Comment by Bubobubobubobubo** [comment]
There are some conflicts to fix with the main branch.

**Comment by Bubobubobubobubo** [comment]
Is the migration done? I can test it whenever I can.

**Comment by Bubobubobubobubo** [comment]
Nice! I'll give it a try whenever I can.

**Comment by Bubobubobubobubo** [comment]
I have merged into the logging branch as a temporary storage for the PR. Some notes after testing:
- looks good when used from the terminal
- the rendering on `fishery web` is weird. We need to find a way to remove the formatters (aka `[red]` from the string that is getting stored in the log file.

**Comment by johnchem** [comment]
As the formatter is only interpreted in the rich handler, when the string is send to through logging lib they stay there.

a way could be to implement the markdown directly into the formatter passed in parameter to the RichHandler (logging.py). 
This way, we can remove the markdown from the message. The impact will be that we will have the same format for all messages with the same level of criticity. I found an example of that on the net during my research but i cannot put my hand on it currently. i will look for that example later.

**Comment by Bubobubobubobubo** [comment]
Rich is not using Markdown but a blend of different markup syntaxes:
1) it supports HTML markdown (not used by Sardine).
2) it supports its own `[xxx]...[/xxx]` based markup, used for color labels, etc. It should be possible to remove it using either a method provided by Rich or using some funky regex.

I did some tests with a .. bad regex and it looks like it is working fairly well just by adding a filter to the JSON configuration in `logger.py` (custom class + declaring it in the config).

**Comment by Bubobubobubobubo** [comment]
BTW feel free to open an issue to talk about that. Speaking in a closed PR is fairly weird :)

**Pull request merged**
